# .goreleaser.yml
project_name: happie
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: "happie_cli"
    dir: .
    main: ./cmd/happie
